"""empty message

Revision ID: 2318edcc0c69
Revises: 
Create Date: 2022-06-03 14:14:16.758350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2318edcc0c69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tbl_account_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('account_type', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.String(length=8), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_type')
    )
    op.create_table('tbl_vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('vendor_name', sa.String(length=64), nullable=False),
    sa.Column('vendor_tin', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_name'),
    sa.UniqueConstraint('vendor_tin')
    )
    op.create_table('tbl_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('account_number', sa.String(length=32), nullable=False),
    sa.Column('account_title', sa.String(length=255), nullable=False),
    sa.Column('account_type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_type_id'], ['tbl_account_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_accounts')
    op.drop_table('tbl_vendors')
    op.drop_table('tbl_account_type')
    op.drop_table('tbl_user')
    # ### end Alembic commands ###
