"""empty message

Revision ID: 348704b4687f
Revises: 
Create Date: 2022-05-27 06:29:12.419385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348704b4687f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_account_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.String(length=8), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_type')
    )
    op.create_table('tbl_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_user')
    op.drop_table('tbl_account_type')
    # ### end Alembic commands ###
