"""empty message

Revision ID: 43efcfc8c94a
Revises: ee9339379462
Create Date: 2022-06-18 10:39:31.601025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43efcfc8c94a'
down_revision = 'ee9339379462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=32), nullable=False),
    sa.Column('account_title', sa.String(length=255), nullable=False),
    sa.Column('account_type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_type_id'], ['account_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
