"""empty message

Revision ID: 534d89daefc0
Revises: d47c5938072b
Create Date: 2022-06-03 09:34:50.372070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534d89daefc0'
down_revision = 'd47c5938072b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=64), nullable=False),
    sa.Column('vendor_tin', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_name'),
    sa.UniqueConstraint('vendor_tin')
    )
    op.drop_table('tbl_vendor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_vendor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vendor_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('vendor_tin', sa.VARCHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_name'),
    sa.UniqueConstraint('vendor_tin')
    )
    op.drop_table('tbl_vendors')
    # ### end Alembic commands ###
