"""empty message

Revision ID: 74f670d54079
Revises: 9db77e42185c
Create Date: 2022-06-03 13:05:50.639245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f670d54079'
down_revision = '9db77e42185c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_account_type', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('tbl_accounts', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('tbl_user', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('tbl_vendors', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_vendors', 'date_modified')
    op.drop_column('tbl_user', 'date_modified')
    op.drop_column('tbl_accounts', 'date_modified')
    op.drop_column('tbl_account_type', 'date_modified')
    # ### end Alembic commands ###
