"""empty message

Revision ID: 92269d5dc229
Revises: 83ae7378df33
Create Date: 2022-07-02 18:09:05.634463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92269d5dc229'
down_revision = '83ae7378df33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=64), nullable=True),
    sa.Column('disbursement_prepared', sa.String(length=32), nullable=True),
    sa.Column('disbursement_check', sa.String(length=32), nullable=True),
    sa.Column('disbursement_audited', sa.String(length=32), nullable=True),
    sa.Column('disbursement_approved', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    # ### end Alembic commands ###
