"""empty message

Revision ID: a6f0b6dd3490
Revises: 
Create Date: 2022-06-13 22:26:10.379868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6f0b6dd3490'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=64), nullable=False),
        sa.Column('password', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('admin', sa.Boolean(), nullable=True),
        sa.Column('registered_on', sa.DateTime(), nullable=True),
        sa.Column('confirmed_on', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_table(
        'account_type',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_type', sa.String(length=64), nullable=False),
        sa.Column('classification', sa.String(length=8), nullable=False),
        sa.Column('priority', sa.String(length=8), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('date_modified', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('account_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_type')
    op.drop_table('user')
    # ### end Alembic commands ###
