"""empty message

Revision ID: ac9cb44904a9
Revises: 92269d5dc229
Create Date: 2022-07-03 05:06:29.003053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9cb44904a9'
down_revision = '92269d5dc229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petty_cash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.DateTime(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.Column('petty_cash_number', sa.String(length=32), nullable=False),
    sa.Column('invoice_number', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('petty_cash_number')
    )
    op.create_table('petty_cash_entry',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('petty_cash_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['petty_cash_id'], ['petty_cash.id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('petty_cash_entry')
    op.drop_table('petty_cash')
    # ### end Alembic commands ###
