"""empty message

Revision ID: d47c5938072b
Revises: 3d82d986a85b
Create Date: 2022-06-03 06:02:52.587280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47c5938072b'
down_revision = '3d82d986a85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=64), nullable=False),
    sa.Column('vendor_tin', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_name'),
    sa.UniqueConstraint('vendor_tin')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_vendor')
    # ### end Alembic commands ###
